### PR TITLE
Added minified version of bootstrap from #berniestrap

### PR DESCRIPTION
**Pull request by randome**
To align the look and feel of the site with other projects we decided to use berniestrap (modified version of bootstrap 3.3.5)

### CODE REVIEW

**Comment by ajwhite** [comment]
Can we be using `bower` for front end dependencies rather than checking them in?

**Comment by randome** [comment]
@ajwhite Sounds good

1. I'll check if the berniestrap is on bower
2. Are we sure? I don't think there will be much frontend dependencies, ember is already added via gem, and just this bootstrap file, are we expecting much more?

**Comment by ajwhite** [comment]
You can depend on it via the repository:

> I'll check if the berniestrap is on bower

```
bower install git@github.com:SandersForPresident/bootstrap.git#master --save
```

> Are we sure? I don't think there will be much frontend dependencies, ember is already added via gem, and just this bootstrap file, are we expecting much more?

I don't think there's ever an excuse to version control front end dependencies in today's age. We're just bypassing the best practice at that point. Is there a reason we're avoiding using a package manager? If it's strictly due to lack of familiarity with front end package managers, as I'm assuming you are mainly back end, I'm happy to help out on that.

**Comment by randome** [comment]
Ok the reason I see for using bower is with updates to the bootstrap framework. I'll set it up

**Comment by schneidmaster** [comment]
+1 for bower. Even if we don't need many more dependencies it is much cleaner in my opinion. For an example of bower + rails see [this project](https://github.com/schneidmaster/gitreports.com) - note the `.bowerrc`, `bower.json`, including asset paths in `config/application.rb`, and resulting includes in the application manifests.

**Comment by randome** [comment]
@ajwhite You're right I am unfamiliar with bower :)
But my main reason is that I like to keep thing simple, so introducing something like `bower` for two know dependencies (a js framework and a stylesheet) seems a bit too much for me.

But you're both right, this should be standard today and @schneidmaster thanks for the example!

**Comment by randome** [comment]
Also It's late right now on my side of the world, I'm going to bed soon and planning on finishing up tomorrow, if any of you want to take over feel free :)

**Comment by schneidmaster** [comment]
Alright I'll get it done :)

**Comment by schneidmaster** [comment]
Closing in favor of #3.

**Pull request closed without merging**
