### PR TITLE
Remove metaprogramming to improve readability.

### PR DESCRIPTION
**Pull request by lukevmorris**
I think this metaprogramming is going to get us into more trouble than it's worth. It's a very heavy hammer and can be very useful for more complex problems. However, here it's used only to remove a small amount of duplication, which comes at the cost of the class's readability.

### CODE REVIEW

**Comment by fozcodes** [comment]
Yeah I agree with that. It may have been a little toooo DRY. And I can stand a bit of repetition if it makes it speeds up onboarding for new people jumping on the project.

Unless there's any objections, I say merge it.

**Comment by lukevmorris** [comment]
Going further, I actually think duplication is healthy, especially in an early project. Wrong abstractions are a large contributor to technical debt, and it's impossible to know what the right abstractions are until we have a ton of examples to pull from.

**Comment by fozcodes** [comment]
Totally agree! Very Sandi Metz.

**Comment by lukevmorris** [comment]
Sandi Metz is my spirit animal.

**Pull request merged**
